"""empty message

Revision ID: 0d807b20a98c
Revises: dc6e72e4ef1a
Create Date: 2018-11-06 22:41:36.088703

"""

# revision identifiers, used by Alembic.
revision = '0d807b20a98c'
down_revision = 'dc6e72e4ef1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
