"""empty message

Revision ID: 128027439a30
Revises: 8fb0bcce84c3
Create Date: 2018-11-06 22:05:05.974785

"""

# revision identifiers, used by Alembic.
revision = '128027439a30'
down_revision = '8fb0bcce84c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
