"""empty message

Revision ID: 3bba25d376d0
Revises: bde9dbf3ec19
Create Date: 2018-11-06 22:43:30.330602

"""

# revision identifiers, used by Alembic.
revision = '3bba25d376d0'
down_revision = 'bde9dbf3ec19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
