"""empty message

Revision ID: 65e53e1a7e51
Revises: 90021951cd70
Create Date: 2018-11-06 22:18:36.555260

"""

# revision identifiers, used by Alembic.
revision = '65e53e1a7e51'
down_revision = '90021951cd70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
