"""empty message

Revision ID: 8fb0bcce84c3
Revises: f3bd08afee27
Create Date: 2018-11-06 21:50:15.150128

"""

# revision identifiers, used by Alembic.
revision = '8fb0bcce84c3'
down_revision = 'f3bd08afee27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
