"""empty message

Revision ID: 90021951cd70
Revises: 128027439a30
Create Date: 2018-11-06 22:13:28.287098

"""

# revision identifiers, used by Alembic.
revision = '90021951cd70'
down_revision = '128027439a30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
