"""empty message

Revision ID: bde9dbf3ec19
Revises: 0d807b20a98c
Create Date: 2018-11-06 22:41:58.982810

"""

# revision identifiers, used by Alembic.
revision = 'bde9dbf3ec19'
down_revision = '0d807b20a98c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
