"""empty message

Revision ID: d140330825ce
Revises: 65e53e1a7e51
Create Date: 2018-11-06 22:20:48.660487

"""

# revision identifiers, used by Alembic.
revision = 'd140330825ce'
down_revision = '65e53e1a7e51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
