"""empty message

Revision ID: dc6e72e4ef1a
Revises: 5fc7e813b43e
Create Date: 2018-11-06 22:40:46.720622

"""

# revision identifiers, used by Alembic.
revision = 'dc6e72e4ef1a'
down_revision = '5fc7e813b43e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
