"""empty message

Revision ID: fe716c34dd57
Revises: d140330825ce
Create Date: 2018-11-06 22:37:55.424645

"""

# revision identifiers, used by Alembic.
revision = 'fe716c34dd57'
down_revision = 'd140330825ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('test', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'test')
    # ### end Alembic commands ###
